/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficos;

import grafo.destino;
import grafo.origen;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import manejadorArchivo.salidaMapa;

/**
 *
 * @author david
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoEntrada = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoArchivoEntrada = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        dialogoEntrada.setSize(new java.awt.Dimension(936, 441));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textoArchivoEntrada.setColumns(20);
        textoArchivoEntrada.setFont(new java.awt.Font("Padauk", 0, 24)); // NOI18N
        textoArchivoEntrada.setRows(5);
        jScrollPane1.setViewportView(textoArchivoEntrada);

        javax.swing.GroupLayout dialogoEntradaLayout = new javax.swing.GroupLayout(dialogoEntrada.getContentPane());
        dialogoEntrada.getContentPane().setLayout(dialogoEntradaLayout);
        dialogoEntradaLayout.setHorizontalGroup(
            dialogoEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEntradaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogoEntradaLayout.setVerticalGroup(
            dialogoEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 1153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 634, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String ruta = manejadorArchivo.abrirArchivo.fileChooser();
        if(ruta!=null){
            textoArchivoEntrada.setText("");
            List <String> entradaTexto = manejadorArchivo.manejador.recuperarTexto(ruta);
            for (int i = 0; i < entradaTexto.size(); i++) {
                textoArchivoEntrada.setText(textoArchivoEntrada.getText()+entradaTexto.get(i)+"\n");
            }
            dialogoEntrada.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    private origen origenes[];
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!textoArchivoEntrada.getText().isEmpty()){            
            String separacionLineas [] = textoArchivoEntrada.getText().split("\n");            
            List <String> datosOrigen = new ArrayList<>();
            List <Integer> datosOrigenPosiciones = new ArrayList<>();
            for (int i = 0; i < separacionLineas.length; i++) {
                String separacionO [] = separacionLineas[i].split("\\|");
                if(separacionO!= null && !datosOrigen.contains(separacionO[0])){
                    datosOrigen.add(separacionO[0]);
                }
            }
            origenes = new origen[datosOrigen.size()];
            List <Integer> posicionesDestino = new ArrayList<>();
            for (int i = 0; i < datosOrigen.size(); i++) {
                for (int j = 0; j < separacionLineas.length; j++) {
                    String separacionO []= separacionLineas[j].split("\\|");
                    if(separacionO[0].equals(datosOrigen.get(i)))
                        posicionesDestino.add(j);
                }
                destino [] destinos = new destino[posicionesDestino.size()];
                for (int j = 0; j < posicionesDestino.size(); j++) {
                    String separacionO [] = separacionLineas[posicionesDestino.get(j)].split("\\|");
                    destinos[j] = new destino(separacionO);
                }
                posicionesDestino.clear();
                origenes[i] = new origen(datosOrigen.get(i), destinos);
            }
            dialogoEntrada.setVisible(false);
        }else if(JOptionPane.showConfirmDialog(null, "No se analizara nada, desea continuar?")==0)dialogoEntrada.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(origenes!=null){
            salidaMapa.escribirMapa(origenes,false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public origen[] getOrigenes() {
        return origenes;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialogoEntrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textoArchivoEntrada;
    // End of variables declaration//GEN-END:variables
}
